// Mocks generated by Mockito 5.4.6 from annotations
// in life_os/test/features/projects/presentation/projects_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:life_os/features/projects/data/projects_repository.dart' as _i2;
import 'package:life_os/features/projects/domain/project_model.dart' as _i4;
import 'package:life_os/features/tasks/data/tasks_repository.dart' as _i5;
import 'package:life_os/features/tasks/domain/task_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProjectsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsRepository extends _i1.Mock
    implements _i2.ProjectsRepository {
  MockProjectsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Project>> watchAllProjects() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllProjects, []),
            returnValue: _i3.Stream<List<_i4.Project>>.empty(),
          )
          as _i3.Stream<List<_i4.Project>>);

  @override
  _i3.Future<List<_i4.Project>> getAllProjects() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProjects, []),
            returnValue: _i3.Future<List<_i4.Project>>.value(<_i4.Project>[]),
          )
          as _i3.Future<List<_i4.Project>>);

  @override
  _i3.Future<_i4.Project?> getProjectById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProjectById, [id]),
            returnValue: _i3.Future<_i4.Project?>.value(),
          )
          as _i3.Future<_i4.Project?>);

  @override
  _i3.Future<void> addProject(_i4.Project? project) =>
      (super.noSuchMethod(
            Invocation.method(#addProject, [project]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProject(_i4.Project? project) =>
      (super.noSuchMethod(
            Invocation.method(#updateProject, [project]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProject, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [TasksRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksRepository extends _i1.Mock implements _i5.TasksRepository {
  MockTasksRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.Task>> watchTasks() =>
      (super.noSuchMethod(
            Invocation.method(#watchTasks, []),
            returnValue: _i3.Stream<List<_i6.Task>>.empty(),
          )
          as _i3.Stream<List<_i6.Task>>);

  @override
  _i3.Stream<List<_i6.Task>> watchTasksForProject(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTasksForProject, [projectId]),
            returnValue: _i3.Stream<List<_i6.Task>>.empty(),
          )
          as _i3.Stream<List<_i6.Task>>);

  @override
  _i3.Future<_i6.Task?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i6.Task?>.value(),
          )
          as _i3.Future<_i6.Task?>);

  @override
  _i3.Future<void> addTask(_i6.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTask(_i6.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
